name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Build widget
        run: pnpm run build:widget

      - name: Copy README
        run: cp README.md packages/bitcoin-kit-widget/README.md

      - name: Copy LICENSE
        run: cp LICENSE packages/bitcoin-kit-widget/LICENSE

      - name: Create .npmrc file
        run: |
          echo "@zeus-network:registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "access=public" >> .npmrc
        working-directory: packages/bitcoin-kit-widget

      - name: Publish to NPM
        run: npm publish --no-git-checks
        working-directory: packages/bitcoin-kit-widget
